version: '3.7'
services:
  postgres:
    image: postgres:10.7-alpine
    container_name: pg
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes: [
      '$HOME/data/postgres/localdb/data:/var/lib/postgresql/data'
    ]
  es7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es7
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  es6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    container_name: es6
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
  redis:
    container_name: redis
    image: redis:4.0.14
    ports:
      - "6379:6379"